### ISSUE TITLE
Run fixtures teardown after test timeout

### ISSUE THREAD

**Issue by dgozman** [microsoft/playwright-test-runner#40]
I see two possible solutions:
- Introduce a separate fixture timeout and run fixtures separately from the test.
- Ensure that we never reuse worker after timeout and teardown all fixtures when shutting down the worker after the timeout.

**Comment by pavelfeldman** [comment]
> Ensure that we never reuse worker after timeout

I thought that was already the case, we should not reuse the worker after the failure, including timeout.
